### PR TITLE
Allow the progress update interval to be configurable

### PR DESCRIPTION
**Pull request by phil000**
Allow the progress update interval of OneTimeDataTransferHandler to be externally configurable via an appSetting

### CODE REVIEW

**Comment by nahk-ivanov** [comment]
Hello @phil000,

Can you elaborate a little bit more on the purpose of the change? Is this to minimize the output in cases when output redirection is enabled?
This looks like a decent change, I just want to evaluate if it should be an additional command line argument or parking it in the app.config is fine.

Thanks!

**Comment by phil000** [comment]
@nahk-ivanov,
We have a DocumentDB export\backup process that takes 20-30 minutes, so we end up with thousands of lines of 'progress' generated every second. It's really just to reduce noise for longer exports as we capture standard output and log it somewhere useful

**Comment by nahk-ivanov** [comment]
@phil000,
Got it! I think I would prefer to pass it as a command line argument, instead of being in the app.config. It should be more flexible that way.
Will include the fix in the next release.

**Comment by nahk-ivanov** [comment]
Lets keep it open for tracking purposes until the change is checked in.

**Comment by nahk-ivanov** [comment]
Resolved in d088bfcfb17f02554ba7b1ab9b0eae376b3388fa.

**Pull request closed without merging**
