### PR TITLE
Added support for RavenDb as a source

### PR DESCRIPTION
**Pull request by saguiitay**
This PR adds support for importing documents from RavenDb into Azure DocumentDb (solves #1)

### CODE REVIEW

**Comment by aliuy** [comment]
Hey @saguiitay - this sounds awesome :grin: 

In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.

**Comment by saguiitay** [comment]
Signed it

**Comment by aliuy** [comment]
Thanks! We are in the process over reviewing your changes.

**Comment by nahk-ivanov** [comment]
Thank you for your contribution! RavenDB support was added in ddfd28b.

**Pull request closed without merging**
